package compiler

import (
	"fmt"

	"github.com/yourfavoritedev/golang-interpreter/ast"
	"github.com/yourfavoritedev/golang-interpreter/code"
	"github.com/yourfavoritedev/golang-interpreter/object"
)

// Compiler will create Bytecode for the VM to execute.
// The Compiler will leverage the evaluated abstract-syntax-tree to
// compile the necessary attributes for Bytecode. This includes the
// instructions (generated bytecode) and constants (the constant pool).
// LastInstruction is the very last instruction that was omitted.
// PreviousInstruction is the one before that.
// symbolTable keeps track of the identifiers observed by the compiler.
type Compiler struct {
	instructions        code.Instructions
	constants           []object.Object
	lastInstruction     EmittedInstruction
	previousInstruction EmittedInstruction
	symbolTable         *SymbolTable
}

// EmittedInstruction is the struct that describes an instruction that was
// emitted by the compiler
type EmittedInstruction struct {
	Opcode   code.Opcode
	Position int
}

// New simply initializes a new Compiler
func New() *Compiler {
	return &Compiler{
		instructions:        code.Instructions{},
		constants:           []object.Object{},
		lastInstruction:     EmittedInstruction{},
		previousInstruction: EmittedInstruction{},
		symbolTable:         NewSymbolTable(),
	}
}

// Compile builds the instructions and constants for the Compiler
// to generate bytecode. It is a recursive function that navigates the AST,
// evaluates the nodes and transform them into constants (object.Objects)
// to be added to the constants pool, and builds the necessary instructions
// for the VM to execute.
func (c *Compiler) Compile(node ast.Node) error {
	switch node := node.(type) {
	// our starting point
	case *ast.Program:
		for _, s := range node.Statements {
			err := c.Compile(s)
			if err != nil {
				return err
			}
		}

	// compile expression statement - work our way down to the expression
	case *ast.ExpressionStatement:
		err := c.Compile(node.Expression)
		if err != nil {
			return err
		}
		c.emit(code.OpPop)

	// compile infix expression - work our way down to the literals
	case *ast.InfixExpression:
		// when a "<" operator is encountered, we want to simply apply the
		// comparison in reverse to keep logic succinct. To the VM, its as if the
		// "<" operator does not exist, all it should worry about is the OpGreaterThan instructions.
		if node.Operator == "<" {
			err := c.Compile(node.Right)
			if err != nil {
				return err
			}

			err = c.Compile(node.Left)
			if err != nil {
				return err
			}

			c.emit(code.OpGreaterThan)
			return nil
		}

		err := c.Compile(node.Left)
		if err != nil {
			return err
		}

		err = c.Compile(node.Right)
		if err != nil {
			return err
		}

		switch node.Operator {
		case "+":
			c.emit(code.OpAdd)
		case "-":
			c.emit(code.OpSub)
		case "*":
			c.emit(code.OpMul)
		case "/":
			c.emit(code.OpDiv)
		case ">":
			c.emit(code.OpGreaterThan)
		case "==":
			c.emit(code.OpEqual)
		case "!=":
			c.emit(code.OpNotEqual)
		default:
			return fmt.Errorf("unknown operator %s", node.Operator)
		}

	// compile prefix expression - work our way down to the literals
	case *ast.PrefixExpression:
		err := c.Compile(node.Right)
		if err != nil {
			return err
		}
		switch node.Operator {
		case "-":
			c.emit(code.OpMinus)
		case "!":
			c.emit(code.OpBang)
		default:
			return fmt.Errorf("unknown operator: %s", node.Operator)
		}

	// compile an if expression - work our way down conditions and block statements
	// when compiling an if expression we run into the question of how to effectively compile
	// the right instructions given that an if-condition by nature has a binary evaluation,
	// a consequence and an alternative. We need to compile the if-expression instructions
	// while also providing additional instructions on where the VM needs to jump as a result
	// of the binary evaluation to execute the right block. This is represented by the
	// code.OpJumpNotTruthy and code.OpJump instructions that get compiled during this step.
	// code.OpJumpNotTruthy - jump over the compiled consequence
	// code.OpJump - jump over the compiled alternative
	case *ast.IfExpression:
		err := c.Compile(node.Condition)
		if err != nil {
			return err
		}

		// Emit an 'OpJumpNotTruthy' with a bogus operand value (absolute offset byte position) which we will resolve through backpatching
		// Recall that code.OpJumpNotTruthy has a single operand that indicates where in the instructions to jump to if the condition is not truthy
		jumpNotTruhyPos := c.emit(code.OpJumpNotTruthy, 9999)

		// compile the consequence
		err = c.Compile(node.Consequence)
		if err != nil {
			return err
		}

		// The consequence is an *ast.ExpressionStatement which emits an OpPop instruction.
		// We want to keep the constant on the stack to have a value for statements that use
		// it as an expression (let x = 5), so we must remove the last pop instruction.
		// OpPop instruction
		if c.lastInstructionIsPop() {
			c.removeLastPop()
		}

		// the code.OpJump instruction is emitted directly after emitting the consequence (almost like its part of the consequence
		// when the consequence is executed by the VM, it knows to jump over the alternative instruction or over a OpNull instruction.
		// when an alternative block exists - it tells us the VM it can skip over the alternative).
		// the OpJump instruction itself is direcly before the alternative or OpNull instruction.
		// The code.OpJump operand will be backpatched with the position of the instruction to be jumped over
		// Emit an `OpJump with bogus value` to be backpatched
		jumpPos := c.emit(code.OpJump, 9999)
		// as soon as the consequence is emitted, we know exactly what to change the code.OpJumpNotTruthy operand to
		// knowing that we need to skip over this truthy instruction (consequence) because OpJumpNotTruthy should execute when the condition is falsey.
		// afterConsequencePos should now be the position of the alternative or OpNull instructiom.
		afterConsequencePos := len(c.instructions)
		// replace code.OpJumpNotTruthy's operand with the new position, the position of the alternatve or OpNull instruction (afterConsequencePos)
		c.changeOperand(jumpNotTruhyPos, afterConsequencePos)

		// if we have no node.Alternative then we need to emit code.OpNull. In the event that the condition is falsey,
		// we need a OpNull instruction for the VM to be able to execute and pop.
		if node.Alternative == nil {
			c.emit(code.OpNull)
		} else {
			// compile the alternative
			err := c.Compile(node.Alternative)
			if err != nil {
				return err
			}

			// same reasoning as above, we want to prevent the constant generated from the alternative
			// from popping so it can be used in the future
			if c.lastInstructionIsPop() {
				c.removeLastPop()
			}
		}

		// as soon as the alternative or OpNull instruction is emitted, we know exactly what to backpatch the code.OpJump operand to
		// knowing that we need to skip over these falsey instructions because OpJump should execute as part of the consequence when the condition is truthy.
		// afterAlternativePos should now be the position after the alternative or OpNull instructiom.
		afterAlternativePos := len(c.instructions)
		// replace code.OpJump's operand with the new position, the position after the alternative or OpNull instruction (afterAlternativePos)
		c.changeOperand(jumpPos, afterAlternativePos)

	// compile a block statement
	case *ast.BlockStatement:
		for _, s := range node.Statements {
			err := c.Compile(s)
			if err != nil {
				return err
			}
		}

	// compile a let statement and update the symbolTable
	case *ast.LetStatement:
		err := c.Compile(node.Value)
		if err != nil {
			return err
		}
		// define the identifier in the symbol table
		symbol := c.symbolTable.Define(node.Name.Value)
		// the symbol for that identifier now has an index, which we use as an operand
		// to construct the OpSetGlobal instruction
		c.emit(code.OpSetGlobal, symbol.Index)

	// compile an identifier, it should look into the symbolTable to validate that the identifier has
	// been previously associated with a symbol.
	case *ast.Identifier:
		// grab the identiier from the symbol table
		symbol, ok := c.symbolTable.Resolve(node.Value)
		if !ok {
			return fmt.Errorf("undefined variable: %s", node.Value)
		}

		// construct an OpGetGlobal instruction with the symbol's index as the operand
		c.emit(code.OpGetGlobal, symbol.Index)

	// compile an array literal, it should cosntruct an OpArray instruction with the operand
	// being the number of elements in the array.
	case *ast.ArrayLiteral:
		// compile all elements in the array. The elements themselves are expressions.
		for _, e := range node.Elements {
			err := c.Compile(e)
			if err != nil {
				return err
			}
		}

		c.emit(code.OpArray, len(node.Elements))

	// compile an integer literal
	case *ast.IntegerLiteral:
		integer := &object.Integer{Value: node.Value}
		c.emit(code.OpConstant, c.addConstant(integer))

	// compile a string literal
	case *ast.StringLiteral:
		s := &object.String{Value: node.Value}
		c.emit(code.OpConstant, c.addConstant(s))

	// compile a boolean literal
	case *ast.Boolean:
		if node.Value {
			c.emit(code.OpTrue)
		} else {
			c.emit(code.OpFalse)
		}
	}

	return nil
}

// addConstant will add the given obj to the end of the constant pool and
// will return the index of that obj, that index can be used as an identifier
// to find obj in the pool.
func (c *Compiler) addConstant(obj object.Object) int {
	c.constants = append(c.constants, obj)
	return len(c.constants) - 1
}

// emit generates an instruction for the compiler using the given params
// and then returns the starting position of the new instruction. The Compiler
// will keep track of the instruction it last emitted.
func (c *Compiler) emit(op code.Opcode, operands ...int) int {
	ins := code.Make(op, operands...)
	pos := c.addInstruction(ins)

	c.setLastInstruction(op, pos)

	return pos
}

// addInstruction builds to the compiler's current instructions. It takes
// the given instruction (ins) and appends it. It returns the starting position of the
// new instruction which should just be where the instructions initially ended + 1 position.
func (c *Compiler) addInstruction(ins []byte) int {
	posNewInstruction := len(c.instructions)
	c.instructions = append(c.instructions, ins...)
	return posNewInstruction
}

// setLastInstruction helps the compiler keep track of the instructions that
// it has emitted. When a new instruction is emitted, the lastInstructon recorded
// will become the previousInstruction and the new instruction will
// become the lastInstruction
func (c *Compiler) setLastInstruction(op code.Opcode, pos int) {
	previous := c.lastInstruction
	last := EmittedInstruction{Opcode: op, Position: pos}

	c.previousInstruction = previous
	c.lastInstruction = last
}

// lastInstructionIsPop simply checks whether the last emitted instruction
// has an Opcode of code.OpPop
func (c *Compiler) lastInstructionIsPop() bool {
	return c.lastInstruction.Opcode == code.OpPop
}

// removeLastPop is used to remove an OpPop instruction from the compiler,
// shortening the instructions to everything up until the OpPop instruction.
func (c *Compiler) removeLastPop() {
	c.instructions = c.instructions[:c.lastInstruction.Position]
	c.lastInstruction = c.previousInstruction
}

// replaceInstruction will replace an instruction starting at the absolute offset (pos)
// with a new instruction
func (c *Compiler) replaceInstruction(pos int, newInstruction []byte) {
	for i := 0; i < len(newInstruction); i++ {
		c.instructions[pos+i] = newInstruction[i]
	}
}

// NewWithState keeps global state in the REPL so the compiler can continue
// to run with the generated bytecode from a previous compilation.
func NewWithState(s *SymbolTable, constants []object.Object) *Compiler {
	compiler := New()
	compiler.symbolTable = s
	compiler.constants = constants
	return compiler
}

// changeOperand will replace the operand of an instruction at the absolute offset (opPos)
// with a new operand. It recreates the instructions with the new operand and swaps
// it with the old instruction.
func (c *Compiler) changeOperand(opPos int, operand int) {
	op := code.Opcode(c.instructions[opPos])
	newInstruction := code.Make(op, operand)

	c.replaceInstruction(opPos, newInstruction)
}

// Bytecode constructs a Bytecode struct using the Compiler's
// instructions and constants
func (c *Compiler) Bytecode() *Bytecode {
	return &Bytecode{
		Instructions: c.instructions,
		Constants:    c.constants,
	}
}

// Bytecode is the struct for the representation of bytecode that
// will be passed to the VM. The Compiler will generate the Instructions
// and the Constants that were evaluated.
type Bytecode struct {
	Instructions code.Instructions
	Constants    []object.Object
}
